drop database if exists Tables_in_pubs;
create database if not exists Tables_in_pubs;
use Tables_in_pubs;
create table if not exists EMPLEADO(
    DNI_EMPLEADO VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DOMICILIO VARCHAR(50),
    PRIMARY KEY (DNI_EMPLEADO)
);
CREATE TABLE IF NOT EXISTS LOCALIDAD(
    COD_LOCALIDAD INT AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    PRIMARY KEY (COD_LOCALIDAD)
);
CREATE TABLE IF NOT EXISTS PUB(
    COD_PUB INT AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    LICENCIA_FICAL VARCHAR(50) NOT NULL,
    DOMICILIO VARCHAR(50),
    FECHA_APERTURA DATE NOT NULL,
    HORARIO ENUM ('HOR1', 'HOR2', 'HOR3') NOT NULL,
    COD_LOCALIDAD INT,
    PRIMARY KEY (COD_PUB),
    FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS EXISTENCIAS(
    COD_ARTICULO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    CANTIDAD INT CHECK(CANTIDAD >= 0),
    PRECIO DECIMAL(10,2) CHECK(PRECIO > 0) NOT NULL,
    COD_PUB INT NOT NULL,
    PRIMARY KEY (COD_ARTICULO),
    FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS PUB_EMPLEADO(
    COD_PUB INT NOT NULL,
    DNI_EMPLEADO VARCHAR(9) NOT NULL,
    FUNCION VARCHAR(50) NOT NULL,
    PRIMARY KEY (COD_PUB, DNI_EMPLEADO),
    FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS TITULAR(
    DNI_TITULAR VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DOMICILIO VARCHAR(50),
    COD_PUB INT NOT NULL,
    PRIMARY KEY (DNI_TITULAR),
    FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);